infra/network-benchmark updated

diff --git a/infra/network-benchmark b/infra/network-benchmark
--- a/infra/network-benchmark
+++ b/infra/network-benchmark
@@ -2,13 +2,16 @@
 set -eu
 
 HOST=${1:-x.jsx.jp}
-BLOCK_SIZE=${2:-20M}
-BLOCK_COUNT=${3:-5}
+BLOCK_COUNT=${2:-5}
+BLOCK_SIZE=${3:-20}M
+SIZE=$(( BLOCK_COUNT * ${BLOCK_SIZE%M} * 1024 ))
 FILE="/tmp/network_test-transfer-$(date +%s%3N)"
 
+dd if=/dev/zero bs=${BLOCK_SIZE} count=${BLOCK_COUNT} of=${FILE} status=none
 cleanup() {
-  if ! ssh ${HOST} "rm -f '$FILE'"; then
-    echo "Warning: Failed to remove remote file '$FILE'" >&2
+  rm -f ${FILE}
+  if ! ssh ${HOST} "rm -f '${FILE}.copied'"; then
+    echo "Warning: Failed to remove remote file '$FILE.copied'" >&2
   fi
 }
 
@@ -17,23 +20,19 @@ trap cleanup EXIT
 upload_benchmark() {
   echo -e "\n=== Upload benchmark"
   local start=$(date +%s%3N)
-  dd if=/dev/zero bs=${BLOCK_SIZE} count=${BLOCK_COUNT} status=progress \
-  | ssh -o Compression=no ${HOST} "cat > '$FILE'"
-  local end=$(date +%s%3N)
-  local duration=$((end - start))
-  local speed=$(echo "scale=2; $BLOCK_COUNT * ${BLOCK_SIZE%M} * 1024 / $duration" | bc)
-  echo "Upload Speed: $speed MB/s"
+  scp -o Compression=no ${FILE} ${HOST}:${FILE}.copied
+  local duration=$(( $(date +%s%3N) - start ))
+  local speed=$(echo "scale=2; $SIZE / $duration" | bc)
+  echo "Upload Speed: $speed MiB/s"
 }
 
 download_benchmark() {
   echo -e "\n=== Download benchmark"
   local start=$(date +%s%3N)
-  ssh -o Compression=no ${HOST} "cat '$FILE'" \
-  | dd of=/dev/null bs=${BLOCK_SIZE} status=progress
-  local end=$(date +%s%3N)
-  local duration=$((end - start))
-  local speed=$(echo "scale=2; $BLOCK_COUNT * ${BLOCK_SIZE%M} * 1024 / $duration" | bc)
-  echo "Download Speed: $speed MB/s"
+  scp -o Compression=no ${HOST}:${FILE}.copied ${FILE}
+  local duration=$(( $(date +%s%3N) - start ))
+  local speed=$(echo "scale=2; $SIZE / $duration" | bc)
+  echo "Download Speed: $speed MiB/s"
 }
 
 upload_benchmark
