Auto/workflow updated

diff --git a/Auto/workflow b/Auto/workflow
--- a/Auto/workflow
+++ b/Auto/workflow
@@ -25,7 +25,7 @@ replace() {
 }
 
 loop() {
-  echo "$(date -Iseconds) automatic workfrow"
+  echo "\e[32m$(date -Iseconds) automatic workflow update start.\e[0m"
   LIST=($(
     ls */.github/workflows/*.yml | awk -F/ '{print $1}' | sort | uniq
   ))
@@ -33,18 +33,20 @@ loop() {
   commit-push() {
     DIR=$1
     echo -e "\n  \e[31m### $DIR ###\e[0m\n"
-    cd $DIR
-    git diff
-    sleep 3
-    git add .github
-    git commit -m "github/workflow updated" -n || echo -e "\e[33mNO commit change\e[0m"
-    git push > /dev/null 2>&1
-    cd - > /dev/null
+    (
+      cd $DIR
+      git diff
+      sleep 3
+      git add .github
+      git commit -m "github/workflow updated" -n || echo -e "\e[33mNO commit change\e[0m"
+      git push > /dev/null 2>&1
+      echo -e "\e[32m$(date -Iseconds) Pushed\e[0m"
+    )
     echo
   }
 
   for i in ${LIST[@]}; do
-    commit-push $i || echo "no completed ($?)"
+    commit-push $i || echo "\e[33mno completed ($?) failed.\e[0m"
     sleep 3
   done
 }
@@ -62,7 +64,7 @@ main() {
   echo ${CMD}
   run-script() {
     time unbuffer ${CMD}
-    echo "$(date -Iseconds) Exit Status Code $?"
+    echo "\e[32m$(date -Iseconds) Exit Status Code $?\e[0m"
   }
   run-script 2>&1 | tee $LOG_FILE
   rm -fr $TEMP_DIR
