daemon bastion updated

diff --git a/daemon/reverse-bastion/reverse-bastion b/daemon/reverse-bastion/reverse-bastion
--- a/daemon/reverse-bastion/reverse-bastion
+++ b/daemon/reverse-bastion/reverse-bastion
@@ -1,6 +1,9 @@
 #!/usr/bin/env bash
 
-TICK_FILE="/tmp/tick-ventura"
+if [[ "$(uname -s)" == "Darwin" ]]; then
+  PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
+fi
+TICK_FILE="/tmp/tick-bastion"
 
 updateNextTick() {
   (
@@ -34,10 +37,10 @@ nextTime() {
 cleanZombie() {
   local PID=$(pgrep -f "ssh -N -T revers-rem-watch")
   if [[ ! -z "$PID" ]]; then
-    echo "$(TZ=Asia/Tokyo gdate -Iseconds) process killing $PID" 1>&2
+    echo "$(TZ=Asia/Tokyo date -Iseconds) process killing $PID" 1>&2
     kill $PID
   else
-    echo "$(TZ=Asia/Tokyo gdate -Iseconds) ssh process notfound" 1>&2
+    echo "$(TZ=Asia/Tokyo date -Iseconds) ssh process notfound" 1>&2
   fi
 }
 
@@ -47,12 +50,12 @@ whileCheck() {
     sleep 60
     nextTime
     if ! nc -vz -w 2 os.jsx.jp 80 > /dev/null 2>&1; then
-      echo "$(TZ=Asia/Tokyo gdate -Iseconds) connection failed" 1>&2
+      echo "$(TZ=Asia/Tokyo date -Iseconds) connection failed" 1>&2
       cleanZombie
       continue
     fi
-    if ! gtimeout 20 ssh -T -p 80 os.jsx.jp echo health-check > /dev/null 2>&1; then
-      echo "$(TZ=Asia/Tokyo gdate -Iseconds) hangup failed" 1>&2
+    if ! timeout 20 ssh -T -p 80 os.jsx.jp echo health-check > /dev/null 2>&1; then
+      echo "$(TZ=Asia/Tokyo date -Iseconds) hangup failed" 1>&2
       cleanZombie
       continue
     fi
@@ -62,8 +65,8 @@ whileCheck() {
 waitForPort() {
   clearTick
   while nc -vz -w 1 os.jsx.jp 80 > /dev/null 2>&1; do
-    echo "$(TZ=Asia/Tokyo gdate -Iseconds) wait for terminate zombie" 1>&2
-    local PID=$(ssh bastion sudo ss -tunlp | grep "0.0.0.0:80 " | awk -Fpid= '{print $2}' | awk -F, '{print $1}')
+    echo "$(TZ=Asia/Tokyo date -Iseconds) wait for terminate zombie" 1>&2
+    local PID=$(ssh bastion sudo ss -tunlp sport = :80 | awk -F 'pid=' '/pid=/ {print $2}' | awk -F, '{print $1}' | head -n1)
     if [[ ! -z "$PID" ]]; then
       ssh bastion sudo kill $PID
     fi
@@ -75,16 +78,16 @@ waitForPort() {
 waitForResolver() {
   clearTick
   while true; do
-    local REMOTE=$(dig +short vpn.jsx.jp)
+    local REMOTE=$(dig +short bastion.jsx.jp)
     if [[ ! -z "$REMOTE" ]]; then
       break
     fi
-    echo "$(TZ=Asia/Tokyo gdate -Iseconds) DNS resolve failed" 1>&2
+    echo "$(TZ=Asia/Tokyo date -Iseconds) DNS resolve failed" 1>&2
     sleep 300
   done
-  PRINT="reverse-ventura - ${REMOTE} from $(hostname) in $(TZ=Asia/Tokyo gdate -Iseconds)"
+  PRINT="reverse-bastion - ${REMOTE} from $(hostname) in $(TZ=Asia/Tokyo date -Iseconds)"
   echo "$PRINT"
-  CHANNEL=infra gtimeout 10 $HOME/bin/post-slack "$PRINT"
+  CHANNEL=infra timeout 10 $HOME/bin/post-slack "$PRINT"
   echo "GlobalIP $(curl -s https://inet-ip.info/ip)"
 }
 
@@ -93,10 +96,10 @@ waitForResolver() {
   whileCheck &
   while true; do
     waitForResolver
-    # ssh-keygen -f "$HOME/.ssh/known_hosts" -R "vpn.jsx.jp" > /dev/null 2>&1
+    # ssh-keygen -f "$HOME/.ssh/known_hosts" -R "bastion.jsx.jp" > /dev/null 2>&1
     waitForPort
     ssh -N -T revers-rem-watch
-    echo "$(TZ=Asia/Tokyo gdate -Iseconds) SSH broken pipe" 1>&2
+    echo "$(TZ=Asia/Tokyo date -Iseconds) SSH broken pipe" 1>&2
     sleep 11.1
   done
 }
